import 'package:get/get.dart';

class Internationalized extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'welcome': 'Welcome to',
          'general-setting': 'Account information',
          'describe': 'This is your reading statistic !',
          'statistic-publication': 'Number of read publications',
          'statistic-reading-hour': 'Number of reading hours',
          'statistic-pageperhour': 'Number of pages per hour',
          'notification': 'Notification',
          'noti-empty': 'You don\'t have any notification',
          'noti-title-empty': 'Title is empty',
          'noti-content-empty': 'Content is empty',
          'noti-description-empty': 'Description is empty',
          'lending-history': 'Lending History',
          'history-empty': 'Your lending history is empty',
          'history-details': 'Lending details',
          'lend-times': 'Lending times',
          'lending-info': 'Lending info',
          'notification-details': 'Notification details',
          'notification-info': 'Notification info',
          'receipt-date': 'Receipt date',
          'receipt-date-unknown': 'Receipt date unknown',
          'return-date': 'Return date',
          'return-date-unknown': 'Return date unknown',
          'real-return-date': 'Real return date',
          'publications-info': 'Publications info',
          'title': 'Title',
          'code': 'Call number',
          'identification-number': 'ISBN number',
          'punishment-info': 'Punishment info',
          'punishment-reason': 'Punishment reason',
          'forfeit': 'Forfeit fee',
          'forfeit-unknown': 'Forfeit unknown',
          'unknown': 'Unknown',
          'rate': 'Rate our app',
          'rate-message':
              'If you like this app, please take a little bit of your time to review it !\nIt really helps us and it shouldn\'t take you more than one minute.',
          'rate-confirm': 'Rate',
          'rate-reject': 'No, thanks',
          'rate-later': 'Later',
          'rate-thank': 'Thanks for your appreciate',
          'star': 'star',
          'setting': 'Setting',
          'setting-profile': 'Profile Setting',
          'setting-profile-email': 'Changing email',
          'setting-profile-email-alt': 'Changing email address',
          'setting-profile-name': 'Changing name',
          'input-new-name': 'Input a new username',
          'setting-notification': 'Notification Setting',
          'setting-notification-library': 'Receive notification from library',
          'setting-notification-system': 'Receive notification from system',
          'choose-avatar': 'Choose your new avatar',
          'camera': 'Camera',
          'gallery': 'Gallery',
          'en': 'English',
          'vi': 'Vietnamese',
          'language': 'App language',
          'active-language': 'English',
          'currency': 'VND',
          //
          'home': 'Home',
          'hello': 'Hello, ',
          'learning-book': 'Learning book',
          'manual-book': 'Manual book',
          'ethics-book': 'Ethics book',
          'search-book': 'Search book',
          'other-publications': 'Others publications',
          'lesson-plan': 'Lesson plan',
          'essay': 'Essay',
          'work-book': 'Workbook',
          'in-stock': 'In stock',
          'no-data': 'No data',
          //
          //
          'bookcase': 'Bookcase',
          'filter': 'Filter:',
          'sort': 'Sort by:',
          'let-add': 'Let\'s add to bookcase !',
          'unread': 'Unread',
          'reading': 'Reading',
          'read': 'Read',
          'title-placeholder': 'Publications name',
          'title-name': 'Title name',
          'author-name': 'Author name',
          'created_at': 'Add at',
          'last_seen': 'Last seen',
          'attention': 'Attention message',
          'read-beyond-message': 'You had read more than',
          'rest-message': 'Let\'s your eyes rest a little bit!',
          'hour': 'Hour',
          'minute': 'Minute',
          'seconds': 'Seconds',
          'table-content': 'Table of contents',
          'bookmark': 'Bookmarks',
          'note': 'Note',
          'search-inbook': 'Search inside the book',
          'input-search': 'Input search',
          'content-of-page': 'Contents of page ...',
          'reading-setting': 'Reading setting',
          'take-note': 'Create note',
          'edit-note': 'Edit note',
          'font-s': 'Font size',
          'font-f-change': 'Change font family',
          'bg-color': 'Background color',
          'content': 'Content',
          'input-content': 'Input content',
          'publication-info': "Book's infomation",
          //
          //
          'search': 'Search',
          'present': 'Present',
          'publication-store': 'Publications',
          'document-store': 'Documents',
          'search-in-publication': 'Search in the publication',
          'search-in-document': 'Search in the document',
          'remain': 'Remain',
          'topic': 'Topic',
          'type-publications': 'Type publications',
          'author': 'Author',
          'subject': 'Subject',
          'publishing-company': 'Publishing Company',
          'search-no-data': 'No results found, please try another keyword!',
          'vote': 'Vote',
          'page': 'Pages',
          'view': 'Views',
          'intro': 'Intro',
          'size': 'Size',
          'cover-type': 'Cover Type',
          'topic-document': 'Topic document',
          'add-to-bookcase': 'Add to bookcase',
          'add-to-bookcase-success': 'Add to bookcase successfully',
          'add-to-bookcase-failure': 'Add to bookcase unsuccessfully',
          'register-bookcase': 'Register lending',
          'register-bookcase-success': 'Register lending successfully',
          'confirm-registration': 'Confirm registration',
          'quantity': 'Quantity',
          'date-appointment': 'Date appointment',
          'no-bookcase':
              'The number of books is not enough or has been borrowed',
          'date-constraint': ' !',
          'data-update': 'Information is updating',
          'hardcover': 'Hardcover',
          'paperback': 'Paperback',
          'pocket-paperback': 'Pocket paperback',
          'ready-lend': 'Ready to lend',
          'out-of-book': 'Out of book',
          'status': 'Status',
          //
          //
          'lending-request': 'Lending Request',
          'search-request': 'Enter request title',
          'status-request': 'Browsing status',
          'select-status': 'Select status',
          'approved': 'Approved',
          'not-approved': 'Not approved',
          'denied': 'Denied',
          'cancel': 'Cancel',
          'no-document-request': 'You currently have no document requests!',
          'search-no-document': 'No results found, please try another keyword!',
          'add-document': 'Add document',
          'add-document-success': 'Add document successfully !',
          'add-document-failure': 'Add document unsuccessfully !',
          'edit': 'Edit',
          'edit-document-success': 'Edit document successfully !',
          'edit-document-failure': 'Edit document unsuccessfully !',
          'delete': 'Delete',
          'delete-document-success': 'Delete document successfully !',
          'delete-document-failure': 'Delete document unsuccessfully !',
          'title-borrow': 'Title borrow',
          'note-borrow': 'Note',
          'reason-for-refusal': 'Reason for refusal',
          'created-date': 'Created date',
          'save-borrow': 'Save document',
          'enter-title-borrow': 'Enter title',
          'enter-title-book': 'Enter title book',
          'enter-author': 'Enter author',
          'please-enter-title-book': 'Please enter title book',
          'please-enter-author': 'Please enter author',
          //
          //
          'reader-card': 'Reader Card',
          'reader-notfound': 'Reader not found',
          'scan-guide': 'Scan code to see information',
          'scan-guide-notfound': 'Barcode not found',
          'name': 'Full name',
          'name-notfound': 'Nameless',
          'card-code': 'Reader card ID',
          'card-code-notfound': 'Reader card ID doesn\'t exist',
          'agent': 'Agent',
          'agent-student': 'Student reader',
          'agent-teacher': 'Teacher reader',
          'subject-group': 'Subject groups',
          'subjectgroup-notfound': 'No subject group',
          'session-year': 'Sessions years',
          'card-expired-date': 'Expired date of card',
          'indefinite-term': 'Sine-die',
          'unit': 'Unit',
          'unit-notfound': 'Unit not found',
          //
          //
          'success': 'Success',
          'failure': 'Failure',
          'input-password': 'Enter the password',
          'input-mail': 'Input email',
          'input-mail-valid': 'Please input email correctly!',
          'input-mail-description':
              'Input email to receive OTP recover password code',
          'save': 'Save',
          'log-in': 'Login',
          'log-in-success': 'Login success',
          'log-in-failure': 'Login failure',
          'log-in-not-exist': 'Account does not exist',
          'log-in-incorrect': 'Incorrect password or account',
          'input-valid-message': 'Make sure your form all filled out',
          'register': 'Register',
          'log-out': 'Logout',
          'username': 'Username',
          'password': 'Password',
          'save-password': 'Remember',
          'forget-password': 'Forgot your password',
          'confirm': 'Confirm',
          'reset-password': 'Reset password',
          'reset-password-description': 'Choose your new password',
          'input-otp': 'OTP code',
          'input-otp-message': 'Please input OTP code !',
          'input-new-password': 'Input new password',
          'input-new-password-message': 'Please input new password !',
          'reinput-password': 'Retype password',
          'reinput-password-message': 'Please input retype password !',
          'constraint-1': 'Contains at least 1 number letter',
          'constraint-2': 'At least 8 letters',
          'password-unmatch': 'Your password is mismatched',
          'password-unmatch-message': 'Please input matched passwords !',
          'password-valid-message': 'Please input valid passwords !',
          'auth-forbidden': 'This account is forbidden',
          'info': 'Info',
          'error': 'Error',
          'error-message': 'Error occurred, please try again',
          'update-password-success': 'Password has been updated successfully',
          'update-profile-success': 'Profile has been updated successfully',
          'otp-expired': 'OTP code invalided or expired',
          'otp-sent': 'OTP code sent successfully',
          'account-non-exist': 'Non-existent account',
          'session-time-out': 'Sessions time out',
          'no-internet-connection': 'No internet connection',
          'try-again': 'Try again',
          'network-error': 'Network Error',
          'network-error-message': 'Failed to get Network Status',
        },
        'vi_VN': {
          'welcome': 'Chào mừng đến với',
          'general-setting': 'Thông tin tài khoản',
          'describe': 'Dưới đây là thống kê số liệu giờ đọc của bạn !',
          'statistic-publication': 'Số sách đã đọc',
          'statistic-reading-hour': 'Số giờ đọc',
          'statistic-pageperhour': 'Số trang mỗi giờ',
          'notification': 'Thông báo',
          'noti-empty': 'Bạn chưa có thông báo nào !',
          'noti-title-empty': 'Tiêu đề trống',
          'noti-content-empty': 'Nội dung trống',
          'noti-description-empty': 'Mô tả trống',
          'lending-history': 'Lịch sử mượn trả',
          'history-empty': 'Lịch sử mượn trả trống',
          'history-details': 'Chi tiết lịch sử',
          'lend-times': 'Lần mượn thứ',
          'lending-info': 'Thông tin mượn trả',
          'notification-details': 'Chi tiết thông báo',
          'notification-info': 'Thông tin thông báo',
          'receipt-date': 'Ngày mượn',
          'receipt-date-unknown': 'Ngày mượn không xác định',
          'return-date': 'Hạn trả',
          'return-date-unknown': 'Hạn trả không xác định',
          'real-return-date': 'Ngày trả',
          'publications-info': 'Thông tin ấn phẩm',
          'title': 'Nhan đề',
          'code': 'Mã xếp giá',
          'identification-number': 'Mã ĐKCB',
          'punishment-info': 'Thông tin phạt thẻ',
          'punishment-reason': 'Lý do phạt',
          'forfeit': 'Số tiền phạt',
          'forfeit-unknown': 'Số tiền phạt không xác định',
          'unknown': 'Không xác định',
          'rate': 'Đánh giá ứng dụng',
          'rate-message': 'Cảm thấy thích chúng tôi ? Hãy để lại đánh giá nhé',
          'rate-confirm': 'Đánh giá',
          'rate-reject': 'Không, cảm ơn',
          'rate-later': 'Để sau',
          'rate-thank': 'Cảm ơn đã đánh giá',
          'star': 'sao',
          'setting': 'Cài đặt',
          'setting-profile': 'Cài đặt tài khoản',
          'setting-profile-email': 'Thay đổi email',
          'setting-profile-email-alt': 'Thay đổi địa chỉ email',
          'setting-profile-name': 'Đổi tên người dùng',
          'input-new-name': 'Nhập tên người dùng mới',
          'setting-notification': 'Cài đặt thông báo',
          'setting-notification-library': 'Nhận thông báo từ thư viện',
          'setting-notification-system': 'Nhận thông báo từ hệ thống',
          'choose-avatar': 'Chọn ảnh đại diện mới',
          'camera': 'Máy ảnh',
          'gallery': 'Thư viện ảnh',
          'en': 'Tiếng Anh',
          'vi': 'Tiếng Việt',
          'language': 'Ngôn ngữ ứng dụng',
          'active-language': 'Tiếng Việt',
          'currency': 'VNĐ',
          //
          //
          'home': 'Trang chủ',
          'hello': 'Xin chào, ',
          'learning-book': 'Sách giáo khoa',
          'manual-book': 'Sách nghiệp vụ',
          'ethics-book': 'Sách đạo đức',
          'search-book': 'Sách tra cứu',
          'other-publications': 'Ấn phẩm khác',
          'lesson-plan': 'Giáo án',
          'essay': 'Luận án',
          'work-book': 'Sách bài tập',
          'in-stock': 'Còn trong kho',
          'no-data': 'Không có dữ liệu',
          //
          //
          'bookcase': 'Tủ sách',
          'filter': 'Bộ lọc đọc:',
          'sort': 'Sắp xếp theo:',
          'let-add': 'Thêm vào tủ sách nào!',
          'unread': 'Chưa đọc',
          'reading': 'Đang đọc',
          'read': 'Đã đọc xong',
          'title-placeholder': 'Tên ấn phẩm',
          'title-name': 'Tên sách',
          'author-name': 'Tên tác giả',
          'created_at': 'Thời gian nhập',
          'last_seen': 'Mới đọc',
          'attention': 'Thông báo nhắc nhở',
          'read-beyond-message': 'Bạn đã đọc quá',
          'rest-message': 'Hãy cho mắt nghỉ ngơi nhé!',
          'hour': 'Giờ',
          'minute': 'Phút',
          'seconds': 'Giây',
          'table-content': 'Mục lục',
          'bookmark': 'Đánh dấu',
          'note': 'Ghi chú',
          'search-inbook': 'Tìm kiếm trong sách',
          'input-search': 'Nhập tìm kiếm',
          'content-of-page': 'Nội dung của trang ...',
          'reading-setting': 'Cài đặt chế độ đọc',
          'take-note': 'Tạo ghi chú',
          'edit-note': 'Sửa ghi chú',
          'font-s': 'Cỡ chữ',
          'font-f-change': 'Thay đổi phông chữ',
          'bg-color': 'Màu nền',
          'content': 'Nội dung',
          'input-content': 'Nhập nội dung',
          'publication-info': 'Thông tin sách',
          //
          //
          'search': 'Tra cứu',
          'present': 'Giới thiệu',
          'publication-store': 'Kho ấn phẩm',
          'document-store': 'Kho tư liệu',
          'search-in-publication': 'Tìm kiếm trong kho ấn phẩm',
          'search-in-document': 'Tìm kiếm trong kho tư liệu',
          'remain': 'Còn trong kho',
          'topic': 'Chủ đề',
          'type-publications': 'Loại ấn phẩm',
          'author': 'Tên tác giả',
          'subject': 'Môn loại',
          'publishing-company': 'Nhà xuất bản',
          'search-no-data':
              'Không tìm thấy kết quả, vui lòng thử từ khóa khác!',
          'vote': 'Xếp hạng',
          'page': 'Trang',
          'view': 'Lượt xem',
          'intro': 'Giới thiệu',
          'size': 'Kích thước',
          'cover-type': 'Loại bìa',
          'topic-document': 'Chủ đề tư liệu',
          'format': 'Định dạng',
          'type-document': 'Loại tư liệu',
          'add-to-bookcase': 'Thêm vào tủ sách',
          'add-to-bookcase-success': 'Thêm vào tủ sách thành công',
          'add-to-bookcase-failure': 'Thêm vào tủ sách thất bại',
          'register-bookcase': 'Đăng ký mượn',
          'register-bookcase-success': 'Đăng ký mượn thành công',
          'confirm-registration': 'Xác nhận đăng ký mượn',
          'quantity': 'Số lượng',
          'date-appointment': 'Ngày hẹn lấy *',
          'no-bookcase': 'Số lượng sách không đủ hoặc đã bị mượn hết!',
          'date-constraint': 'Ngày hẹn lấy phải lớn hơn ngày hiện tại !',
          'data-update': 'Thông tin đang cập nhật',
          'hardcover': 'Bìa cứng',
          'paperback': 'Bìa mềm',
          'pocket-paperback': 'Bìa bỏ túi',
          'ready-lend': 'Sẵn sàng cho mượn',
          'out-of-book': 'Hết',
          'status': 'Trạng thái',
          //
          //
          'lending-request': 'Yêu cầu tài liệu',
          'search-request': 'Nhập tiêu đề yêu cầu',
          'status-request': 'Trạng thái duyệt',
          'select-status': 'Chọn trạng thái',
          'approved': 'Đã duyệt',
          'not-approved': 'Chưa duyệt',
          'denied': 'Bị từ chối',
          'cancel': 'Hủy',
          'no-document-request': 'Bạn đang không có yêu cầu tài liệu nào!',
          'search-no-document':
              'Không tìm thấy kết quả, vui lòng thử từ khóa khác !',
          'add-document': 'Thêm yêu cầu tài liệu',
          'add-document-success': 'Thêm yêu cầu tài liệu thành công !',
          'add-document-failure': 'Thêm yêu cầu tài liệu thất bại !',
          'edit': 'Sửa',
          'edit-document-success': 'Sửa yêu cầu tài liệu thành công',
          'edit-document-failure': 'Sửa yêu cầu tài liệu thất bại !',
          'delete': 'Xóa',
          'delete-document-success': 'Xóa yêu cầu tài liệu thành công',
          'delete-document-failure': 'Xóa yêu cầu tài liệu thất bại !',
          'title-borrow': 'Tiêu đề',
          'note-borrow': 'Ghi chú',
          'reason-for-refusal': 'Lý do từ chối',
          'created-date': 'Ngày tạo',
          'save-borrow': 'Lưu yêu cầu tài liệu',
          'enter-title-borrow': 'Điền tiêu đề',
          'enter-title-book': 'Điền nhan đề',
          'enter-author': 'Điền tác giả',
          'please-enter-title-book': 'Vui lòng điền nhan đề',
          'please-enter-author': 'Vui lòng điền tên tác giả',
          //
          //
          'reader-card': 'Thẻ bạn đọc',
          'reader-notfound': 'Không tìm thấy bạn đọc',
          'scan-guide': 'Quét mã để xem thông tin',
          'scan-guide-notfound': 'Không tìm thấy thông tin',
          'name': 'Họ tên',
          'name-notfound': 'Khuyết danh',
          'card-code': 'Mã thẻ bạn đọc',
          'card-code-notfound': 'Mã không tồn tại',
          'agent': 'Đối tượng',
          'agent-student': 'Bạn đọc học sinh',
          'agent-teacher': 'Bạn đọc giáo viên',
          'subject-group': 'Tổ bộ môn',
          'subjectgroup-notfound': 'Chưa ở trong tổ bộ môn nào',
          'session-year': 'Niên khóa',
          'card-expired-date': 'Ngày hết hạn thẻ',
          'indefinite-term': 'Vô thời hạn',
          'unit': 'Đơn vị',
          'unit-notfound': 'Không có đơn vị nào',
          //
          //
          'success': 'Thành công',
          'failure': 'Thất bại',
          'input-password': 'Nhập mật khẩu',
          'input-mail': 'Nhập email',
          'input-mail-valid': 'Vui lòng điền chính xác email!',
          'input-mail-description': 'Nhập email để nhận OTP đặt lại mật khẩu',
          'save': 'Lưu',
          'log-in': 'Đăng nhập',
          'log-in-success': 'Đăng nhập thành công',
          'log-in-failure': 'Đăng nhập không thành công',
          'log-in-not-exist': 'Tài khoản không tồn tại',
          'log-in-incorrect': 'Mật khẩu hoặc tài khoản không chính xác',
          'input-valid-message': 'Vui lòng điền đầy đủ thông tin đăng nhập',
          'register': 'Đăng ký',
          'log-out': 'Đăng xuất',
          'username': 'Tên đăng nhập',
          'password': 'Mật khẩu',
          'save-password': 'Lưu mật khẩu',
          'forget-password': 'Quên mật khẩu',
          'confirm': 'Xác nhận',
          'reset-password': 'Đặt lại mật khẩu',
          'reset-password-description':
              'Chọn 1 mật khẩu bạn chưa từng dùng trước đây',
          'input-otp': 'Nhập OTP',
          'input-otp-message': 'Vui lòng nhập mã OTP!',
          'input-new-password': 'Nhập mật khẩu mới',
          'input-new-password-message': 'Vui lòng nhập mật khẩu mới!',
          'reinput-password': 'Nhập lại mật khẩu',
          'reinput-password-message': 'Vui lòng nhập lại mật khẩu!',
          'constraint-1': 'Ít nhất chứa 1 chữ số',
          'constraint-2': 'Bao gồm ít nhất 8 ký tự',
          'password-unmatch': 'Mật khẩu không trùng khớp',
          'password-unmatch-message': 'Vui lòng nhập lại mật khẩu trùng khớp!',
          'password-valid-message': 'Vui lòng nhập mật khẩu hợp lệ!',
          'auth-forbidden': 'Tài khoản không có quyền đăng nhập',
          'info': 'Thông báo',
          'error': 'Lỗi',
          'error-message': 'Có lỗi xảy ra, vui lòng thử lại',
          'update-password-success': 'Cập nhật mật khẩu thành công',
          'update-profile-success': 'Cập nhật hồ sơ thành công',
          'otp-expired': 'OTP không đúng hoặc đã hết hạn',
          'otp-sent': 'Gửi thành công mã OTP',
          'account-non-exist': 'Tài khoản không tồn tại',
          'session-time-out': 'Hết phiên đang nhập',
          'no-internet-connection': 'Không có kết nối mạng internet',
          'try-again': 'Thử lại',
          'network-error': 'Lỗi kết nối',
          'network-error-message': 'Không thể lấy được trạng thái kết nối',
        }
      };
}
